image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: ""
  size: 1Gi
